"""
Deterministic post-processing for HTML galleys generated by htmlgen.py.

Applied after AI extraction, before saving to disk. Two checks:

1. strip_abstract — remove abstract text if it leaked into the HTML body
2. check_missing_refs — detect if PDF has a formal References heading but HTML doesn't
"""

import os
import re
import sys

try:
    import fitz  # PyMuPDF
except ImportError:
    fitz = None

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'lib'))
from citations import REFERENCE_HEADING_RE


def _clean(text):
    """Lowercase, strip non-alphanumeric, collapse whitespace."""
    return re.sub(r'\s+', ' ', re.sub(r'[^a-z0-9 ]', '', text.lower())).strip()


def _strip_tags(html):
    """Remove HTML tags."""
    return re.sub(r'<[^>]+>', '', html)


def _first_block(html):
    """Extract the first <p> block's text content."""
    m = re.search(r'<p[^>]*>(.*?)</p>', html, re.DOTALL)
    if m:
        return _strip_tags(m.group(1)).strip()
    return ''


def _overlap_ratio(a, b):
    """Word overlap ratio between two strings (0.0–1.0)."""
    words_a = set(a.split())
    words_b = set(b.split())
    if not words_a or not words_b:
        return 0.0
    intersection = words_a & words_b
    return len(intersection) / min(len(words_a), len(words_b))


def strip_abstract(html, abstract):
    """Remove the first <p> block if it matches the toc.json abstract (>80% word overlap).

    Returns (html, stripped) where stripped is True if abstract was removed.
    """
    if not abstract or len(abstract) < 50:
        return html, False

    first_text = _first_block(html)
    if not first_text:
        return html, False

    ratio = _overlap_ratio(_clean(first_text), _clean(abstract))
    if ratio < 0.8:
        return html, False

    # Remove the first <p>...</p> block
    html = re.sub(r'<p[^>]*>.*?</p>\s*', '', html, count=1, flags=re.DOTALL)
    return html, True


def pdf_has_formal_refs(pdf_path):
    """Check if PDF has a standalone back-matter heading (References, Notes, Bibliography, etc.)."""
    if fitz is None:
        return False
    doc = fitz.open(pdf_path)
    pdf_text = ''.join(p.get_text() for p in doc)
    doc.close()
    for line in pdf_text.split('\n'):
        if REFERENCE_HEADING_RE.match(line.strip()):
            return True
    return False


def html_has_refs(html):
    """Check if HTML contains a back-matter section (References, Notes, Bibliography, etc.)."""
    # Check for headings that match the shared regex
    for m in re.finditer(r'<h[23][^>]*>(.*?)</h[23]>', html, re.DOTALL):
        heading_text = re.sub(r'<[^>]+>', '', m.group(1)).strip()
        if REFERENCE_HEADING_RE.match(heading_text):
            return True
    # Also check for strong-wrapped headings: <p><strong>References</strong></p>
    for m in re.finditer(r'<p>\s*<strong>(.*?)</strong>\s*</p>', html, re.DOTALL):
        heading_text = m.group(1).strip()
        if REFERENCE_HEADING_RE.match(heading_text):
            return True
    return False


def check_missing_refs(html, pdf_path):
    """Return True if PDF has formal References heading but HTML is missing them."""
    return pdf_has_formal_refs(pdf_path) and not html_has_refs(html)


def detect_bad_split(html):
    """Check if AI flagged the article as a bad split via <!-- BAD_SPLIT --> marker."""
    return '<!-- BAD_SPLIT' in html
