#!/usr/bin/env python3
"""Export backfill pipeline results (toc.json from each issue) to Google Sheets.

Usage:
    python3 backfill/sheets_export.py [--dry-run]

Reads all backfill/output/*/toc.json files and publishes a flat row-per-article
spreadsheet to the configured Google Sheet.
"""

import argparse
import json
import os
import sys
from pathlib import Path

SHEET_KEY = '189pMpS12ZuxYtMS2iLYiHKhwp6N972nZSTuNrea8Mos'
CREDS_FILE = os.path.join(os.path.dirname(__file__), '..', 'data-export',
                          'sea-journal-87a19feadadd.json')
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), 'output')

HEADERS = [
    'Volume', 'Issue', 'Date', 'Section', 'Title', 'Authors', 'DOI',
    'PDF Page Start', 'PDF Page End',
    # Book review fields
    'Book Title', 'Book Author', 'Book Year', 'Reviewer', 'Publisher',
    # Enrichment fields (generated by enrich.py)
    'Subjects', 'Disciplines', 'Themes', 'Thinkers', 'Modalities',
    'Methodology', 'Keywords Enriched', 'Summary',
]


def load_all_tocs(output_dir, doi_registry=None):
    """Load and sort all toc.json files by volume/issue.

    Deduplicates by (volume, issue) — if both '<vol>/' and '<vol>.1/' exist
    for single-issue volumes, only the first one found is used.
    """
    try:
        from backfill.generate_xml import lookup_doi
    except ModuleNotFoundError:
        from generate_xml import lookup_doi

    rows = []
    seen_vol_iss = set()
    output_path = Path(output_dir)
    for toc_file in sorted(output_path.glob('*/toc.json')):
        with open(toc_file) as f:
            toc = json.load(f)
        vol = toc.get('volume', 0)
        iss = toc.get('issue', 0)
        key = (vol, iss)
        if key in seen_vol_iss:
            print(f"  Skipping duplicate vol {vol} iss {iss} from {toc_file.parent.name}/",
                  file=sys.stderr)
            continue
        seen_vol_iss.add(key)
        date = toc.get('date', '')
        for article in toc.get('articles', []):
            # Helper for list-to-string
            def join_list(val):
                if isinstance(val, list):
                    return '; '.join(str(v) for v in val)
                return val or ''

            # Look up DOI from registry
            doi = ''
            if doi_registry:
                doi = lookup_doi(doi_registry, article.get('title', ''),
                                 vol, iss, authors=article.get('authors')) or ''

            row = [
                vol, iss, date,
                article.get('section', ''),
                article.get('title', ''),
                article.get('authors', '') or '',
                doi,
                article.get('pdf_page_start', '') or '',
                article.get('pdf_page_end', '') or '',
                # Book review fields
                article.get('book_title', '') or '',
                article.get('book_author', '') or '',
                article.get('book_year', '') or '',
                article.get('reviewer', '') or '',
                article.get('publisher', '') or '',
                # Enrichment fields
                join_list(article.get('subjects')),
                join_list(article.get('disciplines')),
                join_list(article.get('themes')),
                join_list(article.get('thinkers')),
                join_list(article.get('modalities')),
                article.get('methodology', '') or '',
                join_list(article.get('keywords_enriched')),
                article.get('summary', '') or '',
            ]
            rows.append((vol, iss, row))
    # Sort by volume then issue
    rows.sort(key=lambda x: (x[0], x[1]))
    return [r[2] for r in rows]


def export_to_sheets(rows, dry_run=False):
    """Push rows to Google Sheets."""
    all_data = [HEADERS] + rows
    print(f"Total rows: {len(rows)} articles/reviews across all issues")

    if dry_run:
        print("\n-- DRY RUN (first 10 rows) --")
        for row in all_data[:11]:
            print('\t'.join(str(c) for c in row))
        return

    import gspread
    gc = gspread.service_account(filename=CREDS_FILE)
    sh = gc.open_by_key(SHEET_KEY)
    ws = sh.sheet1

    # Clear and write
    ws.clear()
    ws.update(range_name='A1', values=all_data)

    # Bold header row + freeze (columns A through V = 22 columns)
    ws.format('A1:V1', {'textFormat': {'bold': True}})
    ws.freeze(rows=1)

    print(f"Published {len(rows)} rows to: https://docs.google.com/spreadsheets/d/{SHEET_KEY}")


def main():
    parser = argparse.ArgumentParser(description='Export backfill results to Google Sheets')
    parser.add_argument('--dry-run', action='store_true', help='Print rows without uploading')
    args = parser.parse_args()

    if not os.path.isdir(OUTPUT_DIR):
        print(f"Error: output directory not found: {OUTPUT_DIR}", file=sys.stderr)
        sys.exit(1)

    try:
        from backfill.generate_xml import load_doi_registry
    except ModuleNotFoundError:
        from generate_xml import load_doi_registry
    doi_registry = load_doi_registry()
    doi_count = sum(1 for k in doi_registry if isinstance(k, tuple))
    dup_count = sum(len(v) for v in doi_registry.get('_duplicates', {}).values())
    print(f"DOI registry loaded: {doi_count + dup_count} article DOIs")

    rows = load_all_tocs(OUTPUT_DIR, doi_registry=doi_registry)
    if not rows:
        print("No toc.json files found in output/", file=sys.stderr)
        sys.exit(1)

    export_to_sheets(rows, dry_run=args.dry_run)


if __name__ == '__main__':
    main()
